/*
 * Avinash Vadivelu
 * axv200086
 * .004
 */

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.IOException;
import javax.swing.JButton;
import javax.swing.JOptionPane;

/*
 * This class solves a maze generated by another class using the press of a button.
 */

public class MazeSolverSim {
   public static void main(final String args[]) {
      JButton btn = new JButton("Click to solve maze");
      ActionListener actionListener = new ActionListener() {
         public void actionPerformed(ActionEvent event) {
            try {
                MazeSolver.main(args);
            } catch (IOException e) {
                e.printStackTrace();
            }
         }
      };
      btn.setActionCommand("FirstButton");
      btn.addActionListener(actionListener);
      JOptionPane.showMessageDialog(null, btn);
   }
}
